title: Layer Cycle Behavior

description: >
  Custom behavior to cycle through layers (mouse or keyboard group)

compatible: "zmk,behavior-layer-cycle"

include: one_param.yaml

properties:
  label:
    required: true
    type: string
