name: Build ZMK Firmware

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build ZMK firmware
        uses: zmkfirmware/zmk-actions/build@v1
        with:
          board: nice_nano_v2
          shield: footswitch

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: footswitch-firmware
          path: build/zephyr/zmk.uf2
